exports = module.exports =
  // reserved
  { "abstract": true
  , "boolean": true
  , "break": true
  , "byte": true
  , "case": true
  , "catch": true
  , "char": true
  , "class": true
  , "const": true
  , "continue": true
  , "debugger": true
  , "default": true
  , "delete": true
  , "do": true
  , "double": true
  , "else": true
  , "enum": true
  , "export": true
  , "extends": true
  , "false": true
  , "final": true
  , "finally": true
  , "float": true
  , "for": true
  , "function": true
  , "goto": true
  , "if": true
  , "implements": true
  , "impot": true
  , "in": true
  , "instanceof": true
  , "int": true
  , "interface": true
  , "let": true
  , "long": true
  , "native": true
  , "new": true
  , "null": true
  , "package": true
  , "private": true
  , "protected": true
  , "public": true
  , "return": true
  , "short": true
  , "static": true
  , "super": true
  , "switch": true
  , "synchronized": true
  , "this": true
  , "throw": true
  , "throws": true
  , "transient": true
  , "true": true
  , "try": true
  , "typeof": true
  , "var": true
  , "void": true
  , "volatile": true
  , "while": true
  , "with": true
  // predefined
  , "alert": true
  , "all": true
  , "anchor": true
  , "anchors": true
  , "area": true
  , "Array": true
  , "assign": true
  , "blur": true
  , "button": true
  , "checkbox": true
  , "clearInterval": true
  , "clearTimeout": true
  , "clientInformation": true
  , "close": true
  , "closed": true
  , "confirm": true
  , "constructor": true
  , "crypto": true
  , "Date": true
  , "decodeURI": true
  , "decodeURIComponent": true
  , "defaultStatus": true
  , "document": true
  , "element": true
  , "elements": true
  , "embed": true
  , "embeds": true
  , "encodeURI": true
  , "encodeURIComponent": true
  , "escape": true
  , "eval": true
  , "event": true
  , "fileUpload": true
  , "focus": true
  , "form": true
  , "forms": true
  , "frame": true
  , "frames": true
  , "frameRate": true
  , "function": true
  , "getClass": true
  , "hasOwnProperty": true
  , "hidden": true
  , "history": true
  , "image": true
  , "images": true
  , "Infinity": true
  , "isFinite": true
  , "isNaN": true
  , "isPrototypeOf": true
  , "java": true
  , "JavaArray": true
  , "JavaClass": true
  , "JavaObject": true
  , "JavaPackage": true
  , "innerHeight": true
  , "innerWidth": true
  , "layer": true
  , "layers": true
  , "length": true
  , "link": true
  , "location": true
  , "Math": true
  , "mimeTypes": true
  , "name": true
  , "NaN": true
  , "navigate": true
  , "navigator": true
  , "Number": true
  , "Object": true
  , "offscreenBuffering": true
  , "open": true
  , "opener": true
  , "option": true
  , "outerHeight": true
  , "outerWidth": true
  , "packages": true
  , "pageXOffset": true
  , "pageYOffset": true
  , "parent": true
  , "parseFloat": true
  , "parseInt": true
  , "password": true
  , "pkcs11": true
  , "plugin": true
  , "prompt": true
  , "propertyIsEnum": true
  , "prototype": true
  , "radio": true
  , "reset": true
  , "screenX": true
  , "screenY": true
  , "scroll": true
  , "secure": true
  , "select": true
  , "self": true
  , "setInterval": true
  , "setTimeout": true
  , "status": true
  , "String": true
  , "submit": true
  , "taint": true
  , "text": true
  , "textarea": true
  , "top": true
  , "toString": true
  , "undefined": true
  , "unescape": true
  , "untaint": true
  , "valueOf": true
  , "window": true
  // events
  , "onbeforeunload": true
  , "onblur": true
  , "ondragdrop": true
  , "onclick": true
  , "oncontextmenu": true
  , "ondragdrop": true
  , "onerror": true
  , "onfocus": true
  , "onkeydown": true
  , "onkeypress": true
  , "onkeyup": true
  , "onload": true
  , "onmousedown": true
  , "onmousemove": true
  , "onmouseout": true
  , "onmouseover": true
  , "onmouseup": true
  , "onreset": true
  , "onsubmit": true
  , "onunload": true
  }
